# FinBERT(sentiment)

In [ ]:
import pandas as pd

df = pd.read_csv('ESG_Dataset_13000/all_articles_title_dedup.csv')

df['publication_date'] = pd.to_datetime(df['publication_date'])

df.head()

,publication_date,document_title,author_name,source_name,text,source_file
0,2016-03-31,Sustainability - a hot item on board agendasSu...,NaN,NaN,"TODAY, over 3.9 billion or 54 per cent of the ...",EsgNews109.csv
1,2016-06-20,Deutsche Bank aims to raise EUR1bn through soc...,NaN,NaN,Lender anticipates surge in demand from Europe...,EsgNews124.csv
2,2016-08-01,Thailand: Thai bourse scores top liquidity and...,NaN,NaN,The Stock Exchange of Thailand (SET) has revea...,EsgNews92.csv
3,2016-08-07,Fund managers searching for sustainable betsFu...,NaN,NaN,"At SET Social Impact, an event hosted by the S...",EsgNews107.csv
4,2016-10-03,Investing goes fossil free; Divestment does no...,NaN,NaN,Put it down to the rise of the divestment move...,EsgNews119.csv

In [3]:
from transformers import BertTokenizer, BertForSequenceClassification
import torch

model_name = "yiyanghkust/finbert-tone"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertForSequenceClassification.from_pretrained(model_name)

model.eval()

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 201/201 [00:00<00:00, 1162.27it/s, Materializing param=classifier.weight]
BertForSequenceClassification LOAD REPORT from: yiyanghkust/finbert-tone
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30873, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=3, bias=True)
)

In [4]:
def split_text(text, max_len=510):
    tokens = tokenizer.encode(text, add_special_tokens=False)
    chunks = []

    for i in range(0, len(tokens), max_len):
        chunk_tokens = tokens[i:i+max_len]
        chunk_text = tokenizer.decode(chunk_tokens)
        chunks.append(chunk_text)

    return chunks

In [5]:
import numpy as np

def get_chunk_sentiment(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)

    with torch.no_grad():
        outputs = model(**inputs)

    probs = torch.softmax(outputs.logits, dim=1).numpy()[0]

    neu, pos, neg = probs

    return pos, neg, neu

In [6]:
def get_article_sentiment(text):
    chunks = split_text(text)

    pos_list = []
    neg_list=[]
    neu_list=[]

    for chunk in chunks:
        pos, neg, neu = get_chunk_sentiment(chunk)
        pos_list.append(pos)
        neg_list.append(neg)
        neu_list.append(neu)

# calculate mean prob of each chunk
    pos = np.mean(pos_list)                 
    neg = np.mean(neg_list)         
    neu = np.mean(neu_list)              

    return pos,neg,neu

In [12]:
from tqdm import tqdm

pos = []
neg = []
neu = []

for text in tqdm(df['text']):
    s, i, u = get_article_sentiment(str(text))

    pos.append(s)
    neg.append(i)
    neu.append(u)

df['pos'] = pos
df['neg'] = neg
df['neu'] = neu
df['sentiment_article'] = df['pos'] - df['neg']
df['month'] = df['publication_date'].dt.to_period('M')

print(df[['publication_date', 'pos', 'neg', 'neu', 'sentiment_article', 'month']].to_string(index=False))

100%|██████████| 2194/2194 [16:13<00:00,  2.25it/s]

  publication_date       pos       neg       neu  sentiment_article    month
0       2016-03-31  0.466727  0.046095  0.487178           0.420633  2016-03
1       2016-06-20  0.372524  0.000155  0.627321           0.372369  2016-06
2       2016-08-01  0.400394  0.000044  0.599562           0.400350  2016-08
3       2016-08-07  0.000159  0.000023  0.999818           0.000136  2016-08
4       2016-10-03  0.001011  0.000983  0.998006           0.000028  2016-10

In [ ]:
# Monthly aggregation based on article-level probabilities and sentiment
monthly = df.groupby('month').agg(
    FinBERT_positive = ('pos', 'mean'),
    FinBERT_negative = ('neg', 'mean'),
    FinBERT_neutral  = ('neu', 'mean'),
    FinBERT_sentiment = ('sentiment_article', 'mean'),
    article_count    = ('sentiment_article', 'count'),
).reset_index()

print(f"Monthly rows: {len(monthly)}")
print(monthly.to_string(index=False))

Monthly rows: 112
  month  FinBERT_positive  FinBERT_negative  FinBERT_neutral  FinBERT_sentiment  article_count
2016-03          0.466727          0.046095         0.487178           0.420633              1
2016-06          0.372524          0.000155         0.627321           0.372369              1
2016-08          0.200276          0.000034         0.799690           0.200243              2
2016-10          0.001011          0.000983         0.998006           0.000028              1
2016-12          0.305327          0.002772         0.691901           0.302555              2
2017-02          0.000303          0.000261         0.999436           0.000042              1
2017-04          0.135235          0.000248         0.864517           0.134986              1
2017-06          0.108740          0.245125         0.646136          -0.136385              1
2017-07          0.166667          0.019515         0.813819           0.147152              3
2017-09          0.089904          0.026845         0.883251           0.063060              3
2017-10          0.361975          0.000020         0.638005           0.361954              2
2017-11          0.041468          0.000857         0.957675           0.040611              5
2017-12          0.054307          0.000673         0.945020           0.053634              2
2018-01          0.293556          0.000184         0.706260           0.293372              1
2018-02          0.343790          0.000043         0.656167           0.343746              1
2018-03          0.328545          0.004813         0.666642           0.323732              4
2018-04          0.307717          0.000570         0.691713           0.307147              2
2018-05          0.021114          0.060435         0.918450          -0.039321              6
2018-06          0.137937          0.022282         0.839780           0.115655              5
2018-07          0.000116          0.000069         0.999815           0.000047              1
2018-08          0.000771          0.001646         0.997583          -0.000875              5
2018-09          0.135526          0.051821         0.812653           0.083704              9
2018-10          0.075570          0.007018         0.917412           0.068551              3
2018-11          0.171235          0.089376         0.739389           0.081859              3
2018-12          0.000202          0.002055         0.997743          -0.001853              1
2019-01          0.223630          0.039432         0.736938           0.184198              5
2019-02          0.041801          0.036903         0.921296           0.004897             10
2019-03          0.002057          0.002005         0.995938           0.000052              6
2019-04          0.172434          0.066825         0.760742           0.105609              5
2019-05          0.180751          0.003887         0.815362           0.176864              6
2019-06          0.172799          0.034810         0.792391           0.137988             10
2019-07          0.177689          0.118998         0.703313           0.058691              5
2019-08          0.186269          0.002453         0.811278           0.183816              3
2019-09          0.022325          0.090538         0.887138          -0.068213              8
2019-10          0.020854          0.140420         0.838725          -0.119566              7
2019-11          0.107477          0.046285         0.846237           0.061192             13
2019-12          0.149258          0.044862         0.805881           0.104396             19
2020-01          0.334719          0.042679         0.622602           0.292041             16
2020-02          0.206044          0.054250         0.739706           0.151794             25
2020-03          0.211849          0.033115         0.755036           0.178734             16
2020-04          0.413655          0.004034         0.582312           0.409621              7
2020-05          0.191797          0.038652         0.769551           0.153145             13
2020-06          0.123734          0.168395         0.707871          -0.044661              4
2020-07          0.297021          0.051686         0.651294           0.245335             21
2020-08          0.174236          0.138960         0.686805           0.035276             14
2020-09          0.082995          0.084374         0.832631          -0.001378             15
2020-10          0.172803          0.065418         0.761779           0.107385             37
2020-11          0.321584          0.057903         0.620513           0.263681             20
2020-12          0.335515          0.037371         0.627114           0.298144             37
2021-01          0.158888          0.054127         0.786985           0.104761             56
2021-02          0.107569          0.007945         0.884486           0.099624             47
2021-03          0.240844          0.014993         0.744164           0.225851             49
2021-04          0.205096          0.037384         0.757520           0.167713             44
2021-05          0.170158          0.073821         0.756021           0.096337             55
2021-06          0.251966          0.051730         0.696304           0.200235             67
2021-07          0.248607          0.062150         0.689243           0.186458             55
2021-08          0.183382          0.017637         0.798982           0.165745             32
2021-09          0.152136          0.050256         0.797608           0.101880             49
2021-10          0.192614          0.081042         0.726345           0.111572             79
2021-11          0.225363          0.047422         0.727216           0.177941             57
2021-12          0.192805          0.071415         0.735780           0.121390             60
2022-01          0.227760          0.051340         0.720900           0.176419             67
2022-02          0.265883          0.036052         0.698064           0.229831             55
2022-03          0.116956          0.033120         0.849924           0.083837             61
2022-04          0.257789          0.079647         0.662564           0.178142             37
2022-05          0.224149          0.095651         0.680200           0.128498             58
2022-06          0.247312          0.089562         0.663127           0.157750             46
2022-07          0.197537          0.103221         0.699242           0.094317             30
2022-08          0.284158          0.104923         0.610919           0.179235             28
2022-09          0.153650          0.071021         0.775328           0.082629             44
2022-10          0.214244          0.073290         0.712466           0.140954             27
2022-11          0.186153          0.032494         0.781353           0.153659             38
2022-12          0.146922          0.115753         0.737325           0.031169             33
2023-01          0.275904          0.040699         0.683398           0.235205             28
2023-02          0.175583          0.041047         0.783370           0.134536             48
2023-03          0.258392          0.029724         0.711885           0.228668             28
2023-04          0.273336          0.030618         0.696046           0.242718             17
2023-05          0.234147          0.038636         0.727217           0.195511             21
2023-06          0.196420          0.045400         0.758181           0.151020             33
2023-07          0.232360          0.020380         0.747260           0.211981             19
2023-08          0.253840          0.047974         0.698186           0.205865             16
2023-09          0.178415          0.109453         0.712132           0.068963             20
2023-10          0.230928          0.041507         0.727566           0.189421             20
2023-11          0.229267          0.074727         0.696006           0.154541             25
2023-12          0.165386          0.071087         0.763527           0.094299             29
2024-01          0.228463          0.091836         0.679701           0.136627             25
2024-02          0.286430          0.024727         0.688843           0.261703             15
2024-03          0.210753          0.064964         0.724282           0.145789             17
2024-04          0.243091          0.033224         0.723685           0.209867              8
2024-05          0.197251          0.049673         0.753076           0.147579             20
2024-06          0.160105          0.045783         0.794112           0.114322             26
2024-07          0.093685          0.067921         0.838394           0.025764             17
2024-08          0.230332          0.017405         0.752263           0.212928             18
2024-09          0.228091          0.050637         0.721272           0.177453              7
2024-10          0.519460          0.031965         0.448575           0.487496             18
2024-11          0.400794          0.028343         0.570863           0.372451             14
2024-12          0.390492          0.182059         0.427448           0.208433              6
2025-01          0.226826          0.047455         0.725719           0.179370             11
2025-02          0.146951          0.080266         0.772783           0.066685             11
2025-03          0.277409          0.054259         0.668332           0.223149             16
2025-04          0.155898          0.031770         0.812331           0.124128              9
2025-05          0.325270          0.077511         0.597219           0.247760             13
2025-06          0.261653          0.009052         0.729295           0.252601              7
2025-07          0.289090          0.129001         0.581908           0.160089             15
2025-08          0.313101          0.020797         0.666102           0.292304              6
2025-09          0.337295          0.074778         0.587927           0.262517              8
2025-10          0.220607          0.069761         0.709633           0.150846              7
2025-11          0.370160          0.001122         0.628718           0.369038              7
2025-12          0.477590          0.013878         0.508532           0.463711              6
2026-01          0.351894          0.104056         0.544050           0.247838              8
2026-02          0.369663          0.028386         0.601951           0.341277              9
2026-03          0.433473          0.004195         0.562332           0.429278              4

In [16]:
monthly_sentiment = df.groupby('month').agg(
    sentiment_mean = ('sentiment_article', 'mean'),
    sentiment_std  = ('sentiment_article', 'std'),
    sentiment_abs  = ('sentiment_article', lambda x: abs(x).mean()),
    n_articles     = ('sentiment_article', 'count')
).reset_index()
print(monthly_sentiment.to_string(index=False))
monthly_sentiment.to_csv(
    "/Users/helen/BASc/dissertation/coding/monthly_sentiment.csv",
    index=False
)

  month  sentiment_mean  sentiment_std  sentiment_abs  n_articles
2016-03        0.420633            NaN       0.420633           1
2016-06        0.372369            NaN       0.372369           1
2016-08        0.200243       0.282994       0.200243           2
2016-10        0.000028            NaN       0.000028           1
2016-12        0.302555       0.223911       0.302555           2
2017-02        0.000042            NaN       0.000042           1
2017-04        0.134986            NaN       0.134986           1
2017-06       -0.136385            NaN       0.136385           1
2017-07        0.147152       0.302721       0.183857           3
2017-09        0.063060       0.174702       0.113101           3
2017-10        0.361954       0.161992       0.361954           2
2017-11        0.040611       0.092330       0.041699           5
2017-12        0.053634       0.038409       0.053634           2
2018-01        0.293372            NaN       0.293372           1
2018-02        0.343746            NaN       0.343746           1
2018-03        0.323732       0.113180       0.323732           4
2018-04        0.307147       0.180318       0.307147           2
2018-05       -0.039321       0.127915       0.065869           6
2018-06        0.115655       0.148174       0.115655           5
2018-07        0.000047            NaN       0.000047           1
2018-08       -0.000875       0.000437       0.000875           5
2018-09        0.083704       0.215219       0.185580           9
2018-10        0.068551       0.114883       0.068716           3
2018-11        0.081859       0.203181       0.128293           3
2018-12       -0.001853            NaN       0.001853           1
2019-01        0.184198       0.215588       0.184198           5
2019-02        0.004897       0.070422       0.053616          10
2019-03        0.000052       0.001036       0.000814           6
2019-04        0.105609       0.309054       0.230389           5
2019-05        0.176864       0.330858       0.180684           6
2019-06        0.137988       0.224961       0.202076          10
2019-07        0.058691       0.164185       0.132083           5
2019-08        0.183816       0.166254       0.188270           3
2019-09       -0.068213       0.180557       0.107447           8
2019-10       -0.119566       0.214912       0.122180           7
2019-11        0.061192       0.176543       0.110826          13
2019-12        0.104396       0.261976       0.179259          19
2020-01        0.292041       0.336677       0.339135          16
2020-02        0.151794       0.241777       0.203658          25
2020-03        0.178734       0.148591       0.201020          16
2020-04        0.409621       0.188402       0.409621           7
2020-05        0.153145       0.267145       0.221124          13
2020-06       -0.044661       0.389727       0.290715           4
2020-07        0.245335       0.262207       0.288909          21
2020-08        0.035276       0.364721       0.295210          14
2020-09       -0.001378       0.248648       0.143468          15
2020-10        0.107385       0.237565       0.183682          37
2020-11        0.263681       0.211318       0.266174          20
2020-12        0.298144       0.304886       0.345659          37
2021-01        0.104761       0.244245       0.180339          56
2021-02        0.099624       0.146316       0.099900          47
2021-03        0.225851       0.248180       0.236684          49
2021-04        0.167713       0.241889       0.222102          44
2021-05        0.096337       0.287590       0.211274          55
2021-06        0.200235       0.266623       0.226256          67
2021-07        0.186458       0.264930       0.239562          55
2021-08        0.165745       0.262296       0.187265          32
2021-09        0.101880       0.253395       0.182221          49
2021-10        0.111572       0.282137       0.228958          79
2021-11        0.177941       0.262760       0.208241          57
2021-12        0.121390       0.250418       0.177773          60
2022-01        0.176419       0.263426       0.230833          67
2022-02        0.229831       0.309662       0.285212          55
2022-03        0.083837       0.190867       0.122694          61
2022-04        0.178142       0.274142       0.221291          37
2022-05        0.128498       0.296449       0.256574          58
2022-06        0.157750       0.340349       0.275672          46
2022-07        0.094317       0.292630       0.221757          30
2022-08        0.179235       0.312611       0.282457          28
2022-09        0.082629       0.250176       0.171354          44
2022-10        0.140954       0.236289       0.183600          27
2022-11        0.153659       0.250150       0.181392          38
2022-12        0.031169       0.302919       0.214281          33
2023-01        0.235205       0.256867       0.270601          28
2023-02        0.134536       0.289991       0.202753          48
2023-03        0.228668       0.356727       0.262930          28
2023-04        0.242718       0.299333       0.264275          17
2023-05        0.195511       0.282265       0.246560          21
2023-06        0.151020       0.265987       0.226695          33
2023-07        0.211981       0.296795       0.235128          19
2023-08        0.205865       0.237387       0.211130          16
2023-09        0.068963       0.314280       0.227897          20
2023-10        0.189421       0.296238       0.253004          20
2023-11        0.154541       0.298522       0.227212          25
2023-12        0.094299       0.283581       0.188074          29
2024-01        0.136627       0.365105       0.286262          25
2024-02        0.261703       0.309334       0.287597          15
2024-03        0.145789       0.294602       0.214037          17
2024-04        0.209867       0.362194       0.268727           8
2024-05        0.147579       0.232799       0.195938          20
2024-06        0.114322       0.233441       0.187498          26
2024-07        0.025764       0.352724       0.156970          17
2024-08        0.212928       0.285507       0.236397          18
2024-09        0.177453       0.301437       0.247759           7
2024-10        0.487496       0.403310       0.546777          18
2024-11        0.372451       0.338596       0.424711          14
2024-12        0.208433       0.571151       0.458588           6
2025-01        0.179370       0.332360       0.204572          11
2025-02        0.066685       0.284266       0.165730          11
2025-03        0.223149       0.288512       0.262901          16
2025-04        0.124128       0.266362       0.181377           9
2025-05        0.247760       0.317150       0.315662          13
2025-06        0.252601       0.290590       0.254455           7
2025-07        0.160089       0.422496       0.355526          15
2025-08        0.292304       0.359162       0.299507           6
2025-09        0.262517       0.280227       0.270946           8
2025-10        0.150846       0.282468       0.218466           7
2025-11        0.369038       0.369366       0.369038           7
2025-12        0.463711       0.297295       0.463711           6
2026-01        0.247838       0.398154       0.379485           8
2026-02        0.341277       0.298451       0.366296           9
2026-03        0.429278       0.299258       0.429532           4